export const studentData= [{
    "student_name": "Lynn",
    "email": "lburgh0@usa.gov",
    "phone_number": "630-504-7826",
    "gender": "Male"
  }, {
    "student_name": "De",
    "email": "dtireman1@craigslist.org",
    "phone_number": "956-402-5506",
    "gender": "Female"
  }, {
    "student_name": "Morris",
    "email": "mmcmennum2@mashable.com",
    "phone_number": "930-375-3656",
    "gender": "Genderfluid"
  }, {
    "student_name": "Evvy",
    "email": "elander3@kickstarter.com",
    "phone_number": "636-774-6693",
    "gender": "Female"
  }, {
    "student_name": "Iorgo",
    "email": "iseydlitz4@purevolume.com",
    "phone_number": "478-458-3636",
    "gender": "Male"
  }, {
    "student_name": "Heindrick",
    "email": "haharoni5@cyberchimps.com",
    "phone_number": "332-976-8744",
    "gender": "Male"
  }, {
    "student_name": "Marion",
    "email": "mwillgoss6@accuweather.com",
    "phone_number": "618-822-4310",
    "gender": "Female"
  }, {
    "student_name": "Ruthann",
    "email": "ralessandrucci7@mac.com",
    "phone_number": "111-600-7949",
    "gender": "Polygender"
  }, {
    "student_name": "Vassily",
    "email": "vbader8@jiathis.com",
    "phone_number": "874-387-2542",
    "gender": "Male"
  }, {
    "student_name": "Tate",
    "email": "twollacott9@shareasale.com",
    "phone_number": "217-400-6498",
    "gender": "Male"
  }, {
    "student_name": "Shellysheldon",
    "email": "scellea@scientificamerican.com",
    "phone_number": "831-359-8045",
    "gender": "Male"
  }, {
    "student_name": "Milka",
    "email": "mparminterb@kickstarter.com",
    "phone_number": "171-281-4834",
    "gender": "Female"
  }, {
    "student_name": "Starlene",
    "email": "spincottc@toplist.cz",
    "phone_number": "102-483-5195",
    "gender": "Female"
  }, 
  {
    "student_name": "Quintina",
    "email": "qchettoed@cloudflare.com",
    "phone_number": "679-351-8835",
    "gender": "Female"
  }, {
    "student_name": "Wesley",
    "email": "wsteene@wisc.edu",
    "phone_number": "347-325-8177",
    "gender": "Male"
  }, {
    "student_name": "Creighton",
    "email": "cpetfordf@sitemeter.com",
    "phone_number": "380-349-7002",
    "gender": "Male"
  }, {
    "student_name": "Rudolfo",
    "email": "rkearleyg@webnode.com",
    "phone_number": "121-369-7444",
    "gender": "Male"
  }, {
    "student_name": "Chester",
    "email": "cgirauxh@reuters.com",
    "phone_number": "919-697-1053",
    "gender": "Bigender"
  }, {
    "student_name": "Hew",
    "email": "hlaidlawi@paginegialle.it",
    "phone_number": "120-610-6829",
    "gender": "Male"
  }, {
    "student_name": "Lydie",
    "email": "lduberyj@reverbnation.com",
    "phone_number": "836-390-4189",
    "gender": "Female"
  }, {
    "student_name": "Garret",
    "email": "galderk@biglobe.ne.jp",
    "phone_number": "183-478-0774",
    "gender": "Male"
  }, {
    "student_name": "Conney",
    "email": "cpolleyel@dmoz.org",
    "phone_number": "241-557-1714",
    "gender": "Male"
  }, {
    "student_name": "Clayton",
    "email": "cfilippovm@wordpress.org",
    "phone_number": "263-799-7147",
    "gender": "Male"
  }, {
    "student_name": "Link",
    "email": "lstovinen@tripod.com",
    "phone_number": "406-862-5325",
    "gender": "Male"
  }, {
    "student_name": "Catie",
    "email": "crollinso@disqus.com",
    "phone_number": "867-780-9560",
    "gender": "Female"
  }, {
    "student_name": "Sybila",
    "email": "sbenmorep@w3.org",
    "phone_number": "404-606-3724",
    "gender": "Female"
  }, {
    "student_name": "Roxanna",
    "email": "rlowingsq@noaa.gov",
    "phone_number": "316-984-7123",
    "gender": "Female"
  }, {
    "student_name": "Jared",
    "email": "jmurfettr@google.nl",
    "phone_number": "720-759-8155",
    "gender": "Male"
  }, {
    "student_name": "Temp",
    "email": "tscottrells@godaddy.com",
    "phone_number": "238-558-8914",
    "gender": "Male"
  }, {
    "student_name": "Burton",
    "email": "bdymocket@ted.com",
    "phone_number": "662-409-5727",
    "gender": "Male"
  }, {
    "student_name": "Kelcie",
    "email": "kvalaseku@pagesperso-orange.fr",
    "phone_number": "888-812-9272",
    "gender": "Female"
  }, {
    "student_name": "Hugues",
    "email": "hgoodrightv@uol.com.br",
    "phone_number": "660-897-2564",
    "gender": "Male"
  }, {
    "student_name": "Harv",
    "email": "hbodillw@mapy.cz",
    "phone_number": "145-569-0225",
    "gender": "Male"
  }, {
    "student_name": "Ellwood",
    "email": "epiesingx@furl.net",
    "phone_number": "158-316-8101",
    "gender": "Male"
  }, {
    "student_name": "Kassandra",
    "email": "klobey@home.pl",
    "phone_number": "267-965-1402",
    "gender": "Female"
  }, {
    "student_name": "Dawna",
    "email": "dheightz@wp.com",
    "phone_number": "102-236-1977",
    "gender": "Female"
  }, {
    "student_name": "Aindrea",
    "email": "aoldershaw10@vkontakte.ru",
    "phone_number": "196-438-8078",
    "gender": "Female"
  }, {
    "student_name": "Carilyn",
    "email": "cisham11@angelfire.com",
    "phone_number": "528-183-4664",
    "gender": "Polygender"
  }, {
    "student_name": "Johny",
    "email": "jlefleming12@wisc.edu",
    "phone_number": "343-128-9827",
    "gender": "Male"
  }, {
    "student_name": "Cherry",
    "email": "cvivash13@ucoz.ru",
    "phone_number": "726-619-6748",
    "gender": "Female"
  }, {
    "student_name": "Hobard",
    "email": "hsansam14@buzzfeed.com",
    "phone_number": "882-254-0475",
    "gender": "Male"
  }, {
    "student_name": "Carmella",
    "email": "cmoorwood15@google.com.hk",
    "phone_number": "104-655-3716",
    "gender": "Female"
  }, {
    "student_name": "Archibold",
    "email": "akempshall16@chicagotribune.com",
    "phone_number": "562-669-7454",
    "gender": "Male"
  }, {
    "student_name": "Emlen",
    "email": "earias17@whitehouse.gov",
    "phone_number": "270-850-3633",
    "gender": "Male"
  }, {
    "student_name": "Frannie",
    "email": "fgreenhowe18@simplemachines.org",
    "phone_number": "879-254-0807",
    "gender": "Female"
  }, {
    "student_name": "Edin",
    "email": "elyddon19@nature.com",
    "phone_number": "372-412-8391",
    "gender": "Female"
  }, {
    "student_name": "Marion",
    "email": "mraywood1a@qq.com",
    "phone_number": "704-982-6362",
    "gender": "Non-binary"
  }, {
    "student_name": "Ugo",
    "email": "uminchinton1b@house.gov",
    "phone_number": "977-502-5546",
    "gender": "Male"
  }, {
    "student_name": "Albrecht",
    "email": "adunklee1c@163.com",
    "phone_number": "221-970-7133",
    "gender": "Male"
  }, {
    "student_name": "Tony",
    "email": "thellyer1d@eepurl.com",
    "phone_number": "654-146-1938",
    "gender": "Male"
  }]
  